### ISSUE TITLE
下载项目访问失败：http request fail ed: /bin/wget .lua:72: unknown host: raw.githubusercontent.com

### ISSUE THREAD

**Issue by YoisakiYui** [SmileYik/GTNH-OC-AE-Controller#1]
按照给出的指令下载到openos报错http request fail ed: /bin/wget .lua:72: unknown host: raw.githubusercontent.com

**Comment by SmileYik** [comment]
若不能正常下载则请自行将 https://github.com/SmileYik/GTNH-OC-AE-Controller/tree/master/oc 下面的除了 installer.lua 文件的所有 lua 文件手动复制内容进游戏中。
