### ISSUE TITLE
提示http连接失败 使用前端连接似乎正常

### ISSUE THREAD

**Issue by addpromax** [SmileYik/GTNH-OC-AE-Controller#8]
![image](https://github.com/user-attachments/assets/5719b39a-0a39-4708-9daa-2531bcc6a5e8)
前端
![image](https://github.com/user-attachments/assets/a9102a37-28d0-464d-b6f5-362eb0bb39c2)

**Comment by SmileYik** [comment]
你oc端config.lua配置了吗

**Comment by addpromax** [comment]
配置了的

**Comment by SmileYik** [comment]
> 配置了的

方便贴出来看看配置吗

**Comment by addpromax** [comment]
![image](https://github.com/user-attachments/assets/eb5e7289-64bd-4a7b-a7c3-b89e7e3a166e)

**Comment by addpromax** [comment]
![image](https://github.com/user-attachments/assets/359b8dc9-c470-4821-a741-56fe2b841498)
现在倒是开始抽象报错了

**Comment by SmileYik** [comment]
因特网卡装了吗，装上因特网卡 oc里输入指令 ping 111.231.23.21

**Comment by addpromax** [comment]
![image](https://github.com/user-attachments/assets/4afd6d19-0990-4ad9-b86f-e5108d314056)
![image](https://github.com/user-attachments/assets/7ae1ead7-abea-4397-a003-3d068b27cf70)

**Comment by addpromax** [comment]
没反应 但是可以wget下载网络上的东西

**Comment by SmileYik** [comment]
> 没反应 但是可以wget下载网络上的东西

该服务器由玩家自发分享，若无响应则只能考虑自建后端服务器。

**Comment by addpromax** [comment]
> > 没反应 但是可以wget下载网络上的东西
> 
> 该服务器由玩家自发分享，若无响应则只能考虑自建后端服务器。

自建一样不行

**Comment by SmileYik** [comment]
> > > 没反应 但是可以wget下载网络上的东西
> > 
> > 
> > 该服务器由玩家自发分享，若无响应则只能考虑自建后端服务器。
> 
> 自建一样不行

自建服务器与游戏服务器之间的网络必须通畅且可达

**Comment by addpromax** [comment]
> > > > 没反应 但是可以wget下载网络上的东西
> > > 
> > > 
> > > 该服务器由玩家自发分享，若无响应则只能考虑自建后端服务器。
> > 
> > 
> > 自建一样不行
> 
> 自建服务器与游戏服务器之间的网络必须通畅且可达

本地一样不行 我电脑能正常访问前后端

**Comment by SmileYik** [comment]
你尝试本地使用 /oc sc 生成的电脑安装程序试试看呢，依旧用原有配置

**Comment by addpromax** [comment]
![image](https://github.com/user-attachments/assets/9824bab4-b72b-46a9-ba02-48eebe3de7f9)
不可以 本地测试失败

**Comment by SmileYik** [comment]
你配置与网页上配置的一样么

**Comment by SmileYik** [comment]
![image](https://github.com/user-attachments/assets/8d11b216-6bcd-4b2f-ad85-bc8d875c7ac6)
![image](https://github.com/user-attachments/assets/b32d2ca1-a659-4eb2-8840-6bc56ba5b527)
我这也看不全你到配置

**Comment by addpromax** [comment]
![image](https://github.com/user-attachments/assets/28c5db3c-a21f-42a0-856c-96dc47c0982b)
本机测试pei配置

**Comment by SmileYik** [comment]
既然是本机的话，要不你去存档下 opencoumputer文件夹里，找到这个机器硬盘标签相同前缀的文件夹进去，/home/oc-ae/config.lua 直接打开来沾上来看看把

**Comment by addpromax** [comment]
![image](https://github.com/user-attachments/assets/f66ea88a-dc25-46b4-83dd-11ad47fa3eba)

**Comment by SmileYik** [comment]
那具体原因我也不清楚了，公共分享的服务器的朋友他设定的是7天无有效使用链接后会自动删除链接及数据，可能和这个有关系。也可能与oc配置有关系

**Comment by addpromax** [comment]
好吧
